### ISSUE TITLE
P6 Issues

### ISSUE THREAD

**Issue by NC-MXTC** [fidaremi/TaskManager#1]
https://github.com/fidaremi/TaskManager/blob/8e4b9fef11aae287208a2e79daf0d901181328e4/src/main/java/mx/tc/j2se/tasks/AbstractTaskList.java#L58-L61

Why are we no longer sending errors for this conditions?

**Comment by NC-MXTC** [comment]
https://github.com/fidaremi/TaskManager/blob/8e4b9fef11aae287208a2e79daf0d901181328e4/src/main/java/mx/tc/j2se/tasks/AbstractTaskList.java#L77

Suggest to move this to the [TaskListFactory.java](https://github.com/fidaremi/TaskManager/blob/master/src/main/java/mx/tc/j2se/tasks/TaskListFactory.java)

**Comment by NC-MXTC** [comment]
https://github.com/fidaremi/TaskManager/blob/8e4b9fef11aae287208a2e79daf0d901181328e4/src/main/java/mx/tc/j2se/tasks/ArrayTaskListImpl.java#L206-L207

Why can't we get the stream of an empty list?

**Comment by NC-MXTC** [comment]
https://github.com/fidaremi/TaskManager/blob/8e4b9fef11aae287208a2e79daf0d901181328e4/src/test/java/mx/tc/j2se/tasks/tests/ArrayTaskListImplTest.java#L187-L196

it is not clear what you are testing, there are no assertions on given-when-then comments

**Comment by fidaremi** [comment]
Fixed in Practice 6 Second Commit 
https://github.com/fidaremi/TaskManager/commit/ef54491de3272c78bbe6954477f8d2a585e95d55
